### PR TITLE
Add github ci test pipeline.

### PR DESCRIPTION
**Pull request by caic99**
Using the provided `tests/Makefile` as testing routine.

### CODE REVIEW

**Comment by llohse** [comment]
Thank you for this PR. This reminds me that I had planned to add some automated tests for a long time. I will look into it tomorrow.

**Comment by caic99** [comment]
> Thank you for this PR. This reminds me that I had planned to add some automated tests for a long time. I will look into it tomorrow.

In fact, we are facing a problem using `libnpy` with `gcc-10` in a large project. 

> If the header is included by several files it results in multiple definitions of the same variable.

The new "feature"([Default to -fno-common](https://gcc.gnu.org/gcc-10/porting_to.html)) conflicts with the `has_typestring` part within `npy.hpp`. So I plan to fix it by myself.

**Comment by caic99** [comment]
By the way, is it OK to put declaration and implementation all together in one .hpp file? I suggest to split them apart. @llohse

**Comment by llohse** [comment]
> By the way, is it OK to put declaration and implementation all together in one .hpp file? I suggest to split them apart. @llohse

This is common practice for a header-only library. From my point of view, the file is also small enough to not be split into multiple headers. I could be convinced otherwise, though. Do you have a good reason to split them apart?

**Comment by caic99** [comment]
> > By the way, is it OK to put declaration and implementation all together in one .hpp file? I suggest to split them apart. @llohse
> 
> This is common practice for a header-only library. From my point of view, the file is also small enough to not be split into multiple headers. I could be convinced otherwise, though. Do you have a good reason to split them apart?

Would you see #19 .

**Comment by llohse** [comment]
closing in favor of #24

**Pull request closed without merging**
