### PR TITLE
Add support for stream interface

### PR DESCRIPTION
**Pull request by FreddieLiardet**
Add ability to:
 - Load numpy file from an istream
 - Save numpy file to an ostream

### CODE REVIEW

**Comment by FreddieLiardet** [comment]
Hello, is there any update for this?

**Comment by llohse** [comment]
Since I am working on a new C++ API (see #31) -- which is long overdue -- it does not really make sense to merge this just now. My plan is to adapt the new API to expose streams but I did not find the time yet to properly test it. 
I will try to make the changes later today and prepare a new release.

**Comment by FreddieLiardet** [comment]
I've had a look at the new api, it will work for our needs. Closing the pull request as no longer needed. Do you have an eta of when [#31](https://github.com/llohse/libnpy/pull/31) will be merged?

**Comment by llohse** [comment]
Thanks for the feedback. I will merge it and prepare a new release later this week.

**Pull request closed without merging**
